// VanDiary — banco "Preferiresti" per la sezione Gioco.
// Espone window.VD_QUESTIONS = [{ t: testo, l: 'facile'|'medio'|'difficile' }]
// Tutte generate per combinazione dai pool: "Preferiresti A o B?".
// MEDIO usa i nomi del gruppo. Aggiungere una frase a un pool = decine di nuove domande.
(function () {
  const pools = {
    // ---------- FACILE: dilemmi scemi e leggeri ----------
    facile: [
      "starnutire ogni volta che ridi",
      "avere sempre un sassolino nella scarpa",
      "dover cantare invece di parlare per un giorno",
      "avere il singhiozzo per un'ora ogni mattina",
      "indossare scarpe di due numeri più piccole",
      "avere sempre le mani appiccicose",
      "dimenticare sempre il finale dei film",
      "parlare con un accento a caso per una settimana",
      "ridere come una iena a ogni battuta",
      "dover camminare all'indietro nei weekend",
      "avere sempre freddo ai piedi",
      "dover dire sempre la verità per un giorno intero",
      "avere il telefono sempre al 2% di batteria",
      "mangiare solo cibo piccante per un mese",
      "perdere sempre a sasso-carta-forbice",
      "avere una zanzara che ti segue ovunque",
      "dover indossare un cappello ridicolo per un anno",
      "capire tutte le lingue ma rispondere solo a versi",
      "avere le scarpe che cigolano a ogni passo",
      "dover starnutire prima di ogni frase",
      "avere sempre un capello in bocca",
      "dimenticare il nome di chiunque dopo 5 minuti",
      "dover ballare ogni volta che senti musica",
      "mangiare la pizza con l'ananas per sempre",
      "avere sempre sonno alle 15",
      "dover rispondere 'boh' a ogni domanda per un giorno",
      "avere il telecomando che funziona una volta su tre",
      "avere sempre un piede addormentato",
      "dover fare le scale invece dell'ascensore per sempre",
      "avere i lacci che si slacciano da soli",
      "dimenticare sempre dove hai messo le chiavi",
      "dover guardare solo film in bianco e nero",
      "starnutire ogni volta che entri in un negozio",
      "avere i capelli che crescono il doppio più veloci",
      "dover mangiare la minestra con la forchetta",
      "avere sempre la maglietta al contrario senza accorgertene",
      "ridere a ogni momento serio",
      "dover usare solo le maiuscole quando scrivi",
      "avere il naso che fischia quando respiri",
      "dover salutare tutti con un inchino per un mese",
      "avere un terzo braccio ma solo per tre secondi al giorno",
      "parlare solo in rima per una settimana",
      "avere i piedi che profumano di pizza",
      "starnutire bolle di sapone",
      "avere un gatto che ti giudica in silenzio tutto il giorno",
      "poter teletrasportarti ma solo dentro i bagni pubblici",
      "avere sempre una colonna sonora epica quando cammini",
      "sudare profumo di cocco",
      "avere i capelli che cambiano colore con l'umore",
      "dover urlare 'ananas' ogni volta che ti emozioni",
      "avere un piccione come assistente personale",
      "poter parlare con le piante ma sentire solo lamentele",
      "avere un'ombra che fa cose diverse da te",
      "dover camminare come un granchio nei supermercati",
      "ridere ogni volta che qualcuno dice 'grazie'",
      "vedere la musica come colori nell'aria"
    ],

    // ---------- MEDIO: scenari col gruppo (usa i nomi) ----------
    medio: [
      "fare un viaggio in van di 12 ore con Stefano che canta",
      "dividere la stanza d'albergo con Mattia che russa",
      "restare bloccato in ascensore con Leonardo per un'ora",
      "cucinare per tutti insieme a Simona",
      "perderti in una città straniera con Alessandra",
      "fare campeggio sotto la pioggia con Simone",
      "avere Stefano come navigatore per un viaggio intero",
      "organizzare una festa a sorpresa con Mattia",
      "fare la spesa con Leonardo che compra tutto",
      "montare una tenda al buio con Simone",
      "fare un karaoke a duetto con Alessandra",
      "affrontare un trekking di 8 ore con Simona",
      "dividere l'ultima fetta di pizza con Stefano",
      "guidare di notte mentre Mattia racconta storie",
      "fare un escape room con Leonardo che si agita",
      "cucinare una cena per 20 persone con Alessandra",
      "dover svegliare Simone presto ogni mattina",
      "fare un viaggio low cost organizzato da Simona",
      "litigare per la playlist in macchina con Stefano",
      "fare le pulizie di casa con Mattia",
      "perdere il volo insieme a Leonardo",
      "fare un picnic con Alessandra che porta troppo cibo",
      "montare un mobile IKEA con Simone",
      "convincere Simona a fare paracadutismo",
      "passare un weekend in silenzio con Stefano",
      "fare un viaggio in barca con Mattia che ha il mal di mare",
      "sfidare Leonardo a un torneo di carte",
      "organizzare un trasloco con Alessandra",
      "fare una maratona di film horror con Simone",
      "dover dividere il conto al ristorante con Simona",
      "fare un'escursione con Stefano che si perde sempre",
      "passare il Capodanno bloccato in casa con Mattia",
      "decidere le tappe di un on-the-road con Leonardo",
      "ballare tutta la notte con Alessandra",
      "cucinare senza ricetta insieme a Simone",
      "fare un campionato di ping pong contro Simona",
      "tenere un segreto insieme a Stefano",
      "fare un viaggio senza GPS con Mattia",
      "fare un viaggio in van con Martina che cambia idea ogni 5 minuti",
      "restare senza benzina di notte con Bruno",
      "dividere l'ultimo posto letto con Martina",
      "fare un trekking sotto il sole con Bruno che si lamenta",
      "cucinare per tutti mentre Martina assaggia tutto",
      "perderti nella metro di una città enorme con Bruno",
      "organizzare una cena a sorpresa con Martina",
      "fare un karaoke obbligatorio in duetto con Bruno",
      "guidare 10 ore con Martina alla guida",
      "montare la tenda mentre Bruno dà ordini",
      "fare 3 ore di fila con Martina che spinge",
      "dividere il bagno del campeggio con Bruno",
      "fare un escape room con Martina che tocca tutto",
      "affrontare un temporale in tenda con Bruno",
      "decidere il ristorante mentre Martina dice 'per me è uguale'",
      "fare le valigie all'ultimo minuto con Bruno"
    ],

    // ---------- ESTREMO: scelte impossibili e brutali ----------
    difficile: [
      "rinunciare per sempre alla pizza",
      "non poter più ascoltare musica per il resto della vita",
      "vivere senza internet per cinque anni",
      "perdere tutti i ricordi degli ultimi due anni",
      "non poter più mangiare cibo salato",
      "dover dire ad alta voce ogni tuo pensiero",
      "rivivere lo stesso identico giorno per un anno",
      "non poter più dormire più di quattro ore a notte",
      "rinunciare al caffè per sempre",
      "dover camminare scalzo ovunque per sempre",
      "perdere il senso del gusto per dieci anni",
      "non poter più guardare film o serie tv",
      "doverti trasferire in un paese a caso domani",
      "rinunciare a tutti i social per sempre",
      "vivere sempre con lo stesso identico clima",
      "non poter più ridere ad alta voce",
      "fare per sempre un lavoro che odi ma pagatissimo",
      "rinunciare a viaggiare per il resto della vita",
      "non poter più bere niente che non sia acqua",
      "dire addio al tuo cibo preferito per sempre",
      "perdere del tutto la capacità di mentire",
      "non poter più usare le mani per un anno",
      "vivere in una città senza mai vedere il mare",
      "rinunciare a festeggiare il compleanno per sempre",
      "sapere la data esatta della tua morte",
      "non poter più cambiare idea una volta deciso",
      "indossare gli stessi vestiti ogni giorno per dieci anni",
      "perdere tutte le foto che hai mai scattato",
      "non poter più tornare nei posti dove sei già stato",
      "vivere senza dolci per il resto della vita",
      "usare la mano non dominante per sempre",
      "non poter più ascoltare la tua canzone preferita",
      "scegliere un solo amico da rivedere per sempre",
      "passare un anno intero senza parlare con nessuno",
      "dire sempre la verità anche quando ferisce",
      "leggere i messaggi privati dei tuoi amici per un giorno",
      "tagliare metà invitati dal tuo matrimonio",
      "sapere cosa pensano davvero gli altri di te",
      "rinunciare a vincere ogni discussione per sempre",
      "confessare il tuo segreto più imbarazzante in pubblico",
      "vivere un anno senza telefono ma anche senza i tuoi amici",
      "cambiare un errore del passato ma dimenticare una persona",
      "dare un voto sincero in faccia a ogni amico",
      "rinunciare per sempre alla tua opinione su tutto",
      "sapere il giorno esatto di ogni cosa brutta che ti capiterà",
      "essere sempre l'ultima scelta ma vincere sempre alla fine"
    ]
  };

  function buildPreferiresti(level, pool) {
    const out = [];
    for (let i = 0; i < pool.length; i++) {
      for (let j = i + 1; j < pool.length; j++) {
        out.push({ t: "Preferiresti " + pool[i] + " o " + pool[j] + "?", l: level });
      }
    }
    return out;
  }

  let all = [];
  ["facile", "medio", "difficile"].forEach((lv) => {
    all = all.concat(buildPreferiresti(lv, pools[lv]));
  });

  // Mischia (Fisher-Yates)
  for (let i = all.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    const tmp = all[i]; all[i] = all[j]; all[j] = tmp;
  }

  window.VD_QUESTIONS = all;
})();

// ===== Altri giochi di gruppo =====
(function () {
  window.VD_GAMES = {
    // "Chi è più probabile che ___?" (il gruppo punta una persona)
    mostLikely: [
      "si perda anche col navigatore acceso",
      "finisca a parlare con perfetti sconosciuti",
      "dimentichi il portafoglio a casa",
      "pianga davanti a un film",
      "mangi l'ultima fetta di pizza senza chiedere",
      "si addormenti per primo la sera",
      "organizzi tutto il viaggio nei minimi dettagli",
      "arrivi in ritardo all'appuntamento",
      "faccia amicizia col cane di uno sconosciuto",
      "canti a squarciagola in macchina",
      "dimentichi un compleanno importante",
      "spenda troppo in souvenir inutili",
      "si lamenti del caldo tutto il giorno",
      "proponga di fermarsi a mangiare ogni due ore",
      "scatti cento foto allo stesso tramonto",
      "racconti la stessa storia due volte",
      "si metta a ballare per primo",
      "perda le chiavi proprio adesso",
      "litighi per la scelta della playlist",
      "prenoti tutto all'ultimo minuto",
      "diventi il cuoco ufficiale del gruppo",
      "si scotti al sole il primo giorno",
      "faccia tardi ogni mattina",
      "finisca i giga del telefono a metà viaggio",
      "diventi amico del cameriere",
      "proponga una tappa non prevista",
      "dimentichi dove ha parcheggiato il van",
      "porti il doppio delle valigie necessarie",
      "faccia le battute più brutte",
      "si commuova per un panorama",
      "russi più forte di tutti",
      "voglia sempre l'ultima parola",
      "dimentichi il costume proprio al mare",
      "chieda 'siamo arrivati?' ogni dieci minuti",
      "improvvisi un brindisi a sorpresa",
      "si offra di guidare di notte",
      "perda la sfida a sasso-carta-forbice",
      "trovi sempre la scusa per non lavare i piatti",
      "faccia un complimento a caso a uno sconosciuto",
      "si perda dietro a un gatto per strada",
      "dimentichi il caricabatterie in hotel",
      "diventi il fotografo ufficiale del gruppo",
      "rimanga sveglio a guardare le stelle",
      "ordini il piatto più strano del menu",
      "voglia rifare la stessa foto dieci volte",
      "si addormenti durante un film tutti insieme",
      "proponga di svegliarsi all'alba",
      "dimentichi il nome di qualcuno appena conosciuto",
      "finisca le scorte di snack per primo",
      "trasformi una pausa di 5 minuti in mezz'ora"
    ],
    // Verità o Obbligo — Verità (domande)
    truth: [
      "Qual è la cosa più imbarazzante che hai fatto in viaggio?",
      "Chi del gruppo chiameresti per primo in un'emergenza?",
      "Qual è la tua paura più grande?",
      "Hai mai finto di stare male per evitare qualcosa?",
      "Qual è la bugia più grossa che hai detto ai tuoi?",
      "Qual è il tuo guilty pleasure musicale?",
      "Qual è la cosa più infantile che fai ancora?",
      "Qual è il posto più assurdo in cui ti sei addormentato?",
      "Chi del gruppo somiglia di più a te?",
      "Qual è l'ultima cosa che hai cercato su internet?",
      "Qual è il tuo talento più inutile?",
      "Qual è stata la tua figuraccia peggiore?",
      "Cosa porteresti su un'isola deserta?",
      "Qual è la spesa più stupida che hai mai fatto?",
      "Qual è il sogno ricorrente che fai?",
      "Cosa ti fa ridere anche se non dovrebbe?",
      "Qual è la cosa che non rifaresti mai del tuo passato?",
      "Chi è stata la tua prima cotta?",
      "Qual è la tua manìa più strana?",
      "Cosa diresti a te stesso di 10 anni fa?",
      "Qual è il complimento più bello che hai ricevuto?",
      "Qual è la cosa più coraggiosa che hai fatto?",
      "Hai mai mangiato qualcosa caduto per terra?",
      "Qual è la serie che ti vergogni di aver amato?",
      "Qual è il tuo piano di fuga dagli zombie?",
      "Chi chiameresti per aiutarti a nascondere un segreto?",
      "Qual è la cosa più romantica che hai fatto?",
      "Qual è la tua abitudine peggiore in viaggio?",
      "Se potessi leggere nel pensiero di uno qui, di chi?",
      "Qual è il ricordo d'infanzia più bello che hai?"
    ],
    // Verità o Obbligo — Obbligo (penitenze, fattibili in van/gruppo)
    dare: [
      "Imita qualcuno del gruppo finché non indovinano chi è.",
      "Canta il ritornello della prossima canzone che parte.",
      "Parla con un accento straniero per i prossimi 3 minuti.",
      "Fai 10 flessioni adesso.",
      "Manda un messaggio sincero a un amico ringraziandolo.",
      "Lascia scegliere la musica alla persona alla tua destra.",
      "Racconta una barzelletta: se nessuno ride, rifalla.",
      "Fai il verso del tuo animale preferito per 10 secondi.",
      "Balla senza musica per 20 secondi.",
      "Parla in terza persona per i prossimi 5 minuti.",
      "Fatti fare un trucco/pettinatura da chi è alla tua sinistra.",
      "Manda 'ti voglio bene' all'ultima persona che hai sentito.",
      "Fai un complimento sincero a ognuno del gruppo.",
      "Imita come ride la persona di fronte a te.",
      "Resta in equilibrio su un piede mentre rispondi alla prossima domanda.",
      "Inventa un jingle per il vostro viaggio.",
      "Fai la tua miglior posa da copertina di rivista.",
      "Parla solo sussurrando fino al tuo prossimo turno.",
      "Racconta un tuo difetto come se fosse un pregio.",
      "Mima un film: gli altri devono indovinarlo.",
      "Fai un discorso epico di 30 secondi su un oggetto a caso.",
      "Scambia un capo d'abbigliamento con chi ti sta accanto.",
      "Fai il telecronista di quello che succede ora per 1 minuto.",
      "Canta la prossima frase invece di dirla.",
      "Inventa una parola nuova e usala fino a fine giro.",
      "Fai 5 salti urlando il tuo nome.",
      "Imita un personaggio famoso scelto dal gruppo.",
      "Manda un vocale buffo a un amico non presente.",
      "Posa per una foto imbarazzante a scelta del gruppo.",
      "Ringrazia il van come se fosse una persona."
    ],
    // Sfide di gruppo (tutti insieme o a turni)
    challenges: [
      "Tutti in silenzio per 1 minuto: chi parla o ride, perde.",
      "Trovate 3 cose che avete tutti in comune.",
      "Ognuno dice una cosa bella della persona alla sua sinistra.",
      "Inventate una storia, una parola a testa, finché ha senso.",
      "Sfida di sguardi: chi ride per primo paga il prossimo caffè.",
      "Indovinate la canzone canticchiata da uno di voi.",
      "Ognuno racconta il momento più bello del viaggio finora.",
      "Mimo a catena: il primo mima, l'ultimo indovina.",
      "Elencate a turno città italiane senza ripetere: chi sbaglia, fuori.",
      "Tutti propongono la prossima tappa: si vota la migliore.",
      "Ognuno dice un desiderio per il resto del viaggio.",
      "Gara di facce buffe: il gruppo elegge la peggiore.",
      "Dite a turno una parola sul tema 'estate' senza ripetere.",
      "Chi tiene gli occhi aperti più a lungo senza battere ciglio.",
      "Ognuno imita il modo di guidare di un altro del gruppo.",
      "Trovate un soprannome per il van, tutti d'accordo.",
      "Raccontate la giornata di oggi come fosse un film d'azione.",
      "Ognuno confessa una cosa che non sapevate di lui/lei.",
      "Karaoke a sorpresa: parte una canzone, tutti cantano.",
      "Decidete insieme la colonna sonora ufficiale del viaggio.",
      "A turno: una cosa per cui siete grati oggi.",
      "Indovinello a catena: ognuno ne pone uno al vicino.",
      "Gara di brindisi: il più creativo vince.",
      "Tutti raccontano come si sono conosciuti, versione romanzata.",
      "Scegliete insieme la foto del giorno tra quelle scattate."
    ]
  };
})();
